-- DocLingo AI V25 database foundation
-- Run this entire file once in Supabase SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  avatar_url text,
  credits integer not null default 5 check (credits >= 0),
  last_reward_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.credit_transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  amount integer not null,
  transaction_type text not null check (transaction_type in ('signup','tool_use','ad_reward','purchase','admin')),
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.tool_usage (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  tool_id text not null,
  credits_spent integer not null default 2,
  created_at timestamptz not null default now()
);

create table if not exists public.ai_results (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  tool_id text not null,
  title text not null,
  result_text text not null,
  pages_processed integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.credit_transactions enable row level security;
alter table public.tool_usage enable row level security;
alter table public.ai_results enable row level security;

grant select on public.profiles to authenticated;
grant select on public.credit_transactions to authenticated;
grant select, insert on public.tool_usage to authenticated;
grant select, insert, delete on public.ai_results to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists "Users read own profile" on public.profiles;
create policy "Users read own profile" on public.profiles for select to authenticated using ((select auth.uid()) = id);

drop policy if exists "Users read own transactions" on public.credit_transactions;
create policy "Users read own transactions" on public.credit_transactions for select to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "Users read own usage" on public.tool_usage;
create policy "Users read own usage" on public.tool_usage for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "Users insert own usage" on public.tool_usage;
create policy "Users insert own usage" on public.tool_usage for insert to authenticated with check ((select auth.uid()) = user_id);

drop policy if exists "Users read own AI results" on public.ai_results;
create policy "Users read own AI results" on public.ai_results for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "Users insert own AI results" on public.ai_results;
create policy "Users insert own AI results" on public.ai_results for insert to authenticated with check ((select auth.uid()) = user_id);
drop policy if exists "Users delete own AI results" on public.ai_results;
create policy "Users delete own AI results" on public.ai_results for delete to authenticated using ((select auth.uid()) = user_id);

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles(id,email,full_name,avatar_url,credits)
  values(new.id,new.email,coalesce(new.raw_user_meta_data->>'full_name',split_part(new.email,'@',1)),new.raw_user_meta_data->>'avatar_url',5)
  on conflict (id) do nothing;
  insert into public.credit_transactions(user_id,amount,transaction_type,description) values(new.id,5,'signup','Welcome credits');
  return new;
end;$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

-- Backfill users created before V25.
insert into public.profiles(id,email,full_name,avatar_url,credits)
select id,email,coalesce(raw_user_meta_data->>'full_name',split_part(email,'@',1)),raw_user_meta_data->>'avatar_url',5 from auth.users
on conflict (id) do nothing;

create or replace function public.spend_credits(credit_amount integer) returns integer language plpgsql security definer set search_path = public as $$
declare balance integer; uid uuid := auth.uid();
begin
  if uid is null then raise exception 'Sign in required'; end if;
  if credit_amount <= 0 or credit_amount > 50 then raise exception 'Invalid credit amount'; end if;
  update profiles set credits=credits-credit_amount,updated_at=now() where id=uid and credits>=credit_amount returning credits into balance;
  if balance is null then raise exception 'Not enough credits'; end if;
  insert into credit_transactions(user_id,amount,transaction_type,description) values(uid,-credit_amount,'tool_use','Document tool usage');
  return balance;
end;$$;

create or replace function public.claim_demo_reward(reward_amount integer default 2) returns integer language plpgsql security definer set search_path = public as $$
declare balance integer; uid uuid := auth.uid(); last_claim timestamptz;
begin
  if uid is null then raise exception 'Sign in required'; end if;
  if reward_amount <> 2 then raise exception 'Invalid reward amount'; end if;
  select last_reward_at into last_claim from profiles where id=uid for update;
  if last_claim is not null and last_claim > now()-interval '30 seconds' then raise exception 'Please wait before claiming another reward'; end if;
  update profiles set credits=credits+reward_amount,last_reward_at=now(),updated_at=now() where id=uid returning credits into balance;
  insert into credit_transactions(user_id,amount,transaction_type,description) values(uid,reward_amount,'ad_reward','Demo rewarded-ad credit');
  return balance;
end;$$;

revoke all on function public.spend_credits(integer) from public;
revoke all on function public.claim_demo_reward(integer) from public;
grant execute on function public.spend_credits(integer) to authenticated;
grant execute on function public.claim_demo_reward(integer) to authenticated;
