import React,{useMemo,useState}from"react";import{PDFDocument,degrees,StandardFonts,rgb}from"pdf-lib";import{Archive,Scissors,Eraser,RotateCw,ListOrdered,Hash,CheckCircle2,X,Wand2,Globe2,Search,FileUp,ShieldCheck,Lock,Clock,Eye,Mail,FileText,Sparkles,Languages,BookOpenCheck,Presentation}from"lucide-react";
const base=[['merge','Merge PDF','دمج PDF',Archive,'Combine PDFs','ادمج ملفات PDF'],['split','Split PDF','تقسيم PDF',Scissors,'Extract pages','استخرج صفحات'],['remove','Remove Pages','حذف صفحات',Eraser,'Remove selected pages','احذف صفحات محددة'],['rotate','Rotate PDF','تدوير PDF',RotateCw,'Rotate pages','دوّر صفحات'],['reorder','Reorder Pages','ترتيب الصفحات',ListOrdered,'Custom order','رتب الصفحات'],['numbers','Add Page Numbers','ترقيم الصفحات',Hash,'Add page numbers','أضف أرقام صفحات']];
const extra=[['pdf-translator','PDF Translator','ترجمة PDF',Languages,'Beta'],['word-translator','Word Translator','ترجمة Word',Languages,'Beta'],['pdf-summarizer','PDF Summarizer','تلخيص PDF',Sparkles,'Beta'],['extract-questions','Extract Questions','استخراج أسئلة',FileText,'Beta'],['student','Student Mode','وضع الطالب',BookOpenCheck,'Beta'],['ppt','Create PowerPoint','توليد عرض',Presentation,'Coming Soon']];
const tools=[...base.map(x=>({id:x[0],title:x[1],ar:x[2],icon:x[3],status:'Available',cat:'PDF',desc:x[4],arDesc:x[5]})),...extra.map(x=>({id:x[0],title:x[1],ar:x[2],icon:x[3],status:x[4],cat:'AI',desc:'AI tool will be activated soon.',arDesc:'أداة ذكاء اصطناعي سيتم تفعيلها قريبًا.'}))];
function download(bytes,name){let b=new Blob([bytes],{type:'application/pdf'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(u)}
function pageList(s,total,rtl,emptyAll=true){s=(s||'').trim();if(!s&&emptyAll)return[...Array(total)].map((_,i)=>i);if(!s)throw Error(rtl?'اكتب الصفحات المطلوبة':'Enter pages');let out=[];for(let p of s.split(',').map(x=>x.trim()).filter(Boolean)){if(p.includes('-')){let[a,b]=p.split('-').map(Number);if(!a||!b||a>b)throw Error(rtl?'صيغة غير صحيحة':'Invalid range');for(let i=a;i<=b;i++)out.push(i)}else{let n=Number(p);if(!n)throw Error(rtl?'رقم غير صحيح':'Invalid page');out.push(n)}}if(out.some(n=>n<1||n>total))throw Error(rtl?`أدخل صفحات بين 1 و ${total}`:`Enter pages between 1 and ${total}`);return[...new Set(out)].map(n=>n-1)}
function Shell({lang,onClose,title,Icon,children,desc}){let r=lang==='ar';return <div className="overlay" onClick={onClose}><div className="modal" dir={r?'rtl':'ltr'} onClick={e=>e.stopPropagation()}><button className="close" onClick={onClose}><X size={18}/></button><div className="modalIcon"><Icon size={24}/></div><h2>{title}</h2>{desc&&<p>{desc}</p>}{children}</div></div>}
function FileLine({file}){return file?<div className="ok"><CheckCircle2 size={15}/>{file.name}</div>:null}
function Error({msg}){return msg?<div className="err">{msg}</div>:null}
function PdfTool({tool,lang,onClose}){let r=lang==='ar', [file,setFile]=useState(null),[files,setFiles]=useState([]),[pages,setPages]=useState(tool.id==='reorder'?'1,2,3':tool.id==='split'||tool.id==='remove'?'1':''),[angle,setAngle]=useState('90'),[start,setStart]=useState('1'),[err,setErr]=useState(''),[busy,setBusy]=useState(false);let Icon=tool.icon;
async function run(){setErr('');try{setBusy(true);if(tool.id==='merge'){if(files.length<2)throw Error(r?'اختر ملفين على الأقل':'Choose at least two files');let out=await PDFDocument.create();for(let f of files){let pdf=await PDFDocument.load(await f.arrayBuffer());let ps=await out.copyPages(pdf,pdf.getPageIndices());ps.forEach(p=>out.addPage(p))}download(await out.save(),'doclingo-merged.pdf')}
else{if(!file)throw Error(r?'اختر ملف PDF أولًا':'Choose a PDF first');let src=await PDFDocument.load(await file.arrayBuffer());if(tool.id==='split'){let idx=pageList(pages,src.getPageCount(),r,false),out=await PDFDocument.create();(await out.copyPages(src,idx)).forEach(p=>out.addPage(p));download(await out.save(),'doclingo-split.pdf')}
if(tool.id==='remove'){let rem=new Set(pageList(pages,src.getPageCount(),r,false)),keep=src.getPageIndices().filter(i=>!rem.has(i));if(!keep.length)throw Error(r?'لا يمكن حذف كل الصفحات':'Cannot remove all pages');let out=await PDFDocument.create();(await out.copyPages(src,keep)).forEach(p=>out.addPage(p));download(await out.save(),'doclingo-pages-removed.pdf')}
if(tool.id==='rotate'){pageList(pages,src.getPageCount(),r,true).forEach(i=>src.getPage(i).setRotation(degrees(Number(angle))));download(await src.save(),'doclingo-rotated.pdf')}
if(tool.id==='reorder'){let idx=pageList(pages,src.getPageCount(),r,false),out=await PDFDocument.create();(await out.copyPages(src,idx)).forEach(p=>out.addPage(p));download(await out.save(),'doclingo-reordered.pdf')}
if(tool.id==='numbers'){let font=await src.embedFont(StandardFonts.Helvetica);src.getPages().forEach((p,i)=>{let{width}=p.getSize();p.drawText(String(Number(start||1)+i),{x:width/2-6,y:22,size:11,font,color:rgb(.15,.15,.15)})});download(await src.save(),'doclingo-numbered.pdf')}}}catch(e){setErr(e.message)}finally{setBusy(false)}}
return <Shell lang={lang} onClose={onClose} title={r?tool.ar:tool.title} Icon={Icon} desc={r?tool.arDesc:tool.desc}>{tool.id==='merge'?<><input className="inp" type="file" accept="application/pdf,.pdf" multiple onChange={e=>{let arr=Array.from(e.target.files||[]);setFiles(prev=>[...prev,...arr]);e.target.value=''}} />{files.map((f,i)=><div className="ok" key={f.name+i}><CheckCircle2 size={15}/>{f.name}</div>)}{files.length>0&&<button className="btn secondary full" onClick={()=>setFiles([])}>{r?'مسح الملفات':'Clear files'}</button>}</>:<><input className="inp" type="file" accept="application/pdf,.pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/><FileLine file={file}/>{['split','remove','reorder'].includes(tool.id)&&<input className="inp" value={pages} onChange={e=>setPages(e.target.value)} placeholder={r?'مثال: 1-3,5':'Example: 1-3,5'}/>} {tool.id==='rotate'&&<><input className="inp" value={pages} onChange={e=>setPages(e.target.value)} placeholder={r?'فارغ للكل أو 1-3':'Empty for all or 1-3'}/><select className="inp" value={angle} onChange={e=>setAngle(e.target.value)}><option value="90">90°</option><option value="180">180°</option><option value="270">270°</option></select></>} {tool.id==='numbers'&&<input className="inp" value={start} onChange={e=>setStart(e.target.value)} placeholder={r?'ابدأ من رقم':'Start number'}/>}</>}<Error msg={err}/><button className="btn primary full" disabled={busy} onClick={run}>{busy?(r?'جاري المعالجة...':'Processing...'):(r?'معالجة وتحميل':'Process and download')}</button></Shell>}
function Placeholder({tool,lang,onClose}){let r=lang==='ar';return <Shell lang={lang} onClose={onClose} title={r?tool.ar:tool.title} Icon={tool.icon} desc={r?'هذه الأداة ضمن خطة التفعيل القادمة.':'This tool is on the activation roadmap.'}><button className="btn primary full" onClick={onClose}>{r?'تمام':'Got it'}</button></Shell>}
function Card({tool,lang,onClick}){let I=tool.icon,r=lang==='ar';return <article className="card"><div className="cardTop"><span className={'badge '+tool.status.toLowerCase().replace(' ','-')}>{tool.status}</span><div className="icon"><I size={20}/></div></div><h3>{r?tool.ar:tool.title}</h3><p>{r?tool.arDesc:tool.desc}</p><button className="btn primary full" onClick={onClick}>{tool.status==='Coming Soon'?(r?'تفاصيل':'Details'):(r?'جرّب الآن':'Try now')}</button></article>}
export default function App(){let[lang,setLang]=useState('en'),[cat,setCat]=useState('All'),[q,setQ]=useState(''),[modal,setModal]=useState(null),[fileName,setFileName]=useState('');let r=lang==='ar';let filtered=useMemo(()=>tools.filter(t=>(cat==='All'||t.cat===cat)&&(!q||t.title.toLowerCase().includes(q.toLowerCase())||t.ar.includes(q))),[cat,q]);return <div dir={r?'rtl':'ltr'}><div className="banner">{r?'نسخة تجريبية — أدوات PDF تعمل داخل المتصفح.':'Beta version — PDF tools run in browser.'}</div><header><div className="brand"><div className="logo"><Wand2 size={20}/></div><div><b>DocLingo AI</b><small>doclingo-ai.netlify.app</small></div></div><div><button className="btn secondary" onClick={()=>setLang(r?'en':'ar')}><Globe2 size={16}/>{r?'English':'العربية'}</button></div></header><main><section className="hero"><div><span className="pill">{r?'وصول مجاني للنسخة التجريبية':'Free beta access'}</span><h1>{r?'ترجم، حوّل، ولخّص ملفاتك بالذكاء الاصطناعي':'Translate, convert, and summarize documents with AI'}</h1><p>{r?'منصة عالمية لأدوات PDF وWord وPowerPoint.':'A global toolkit for PDF, Word, and PowerPoint.'}</p><div className="trust"><span><ShieldCheck size={16}/>{r?'خصوصية':'Privacy'}</span><span><Lock size={16}/>{r?'داخل المتصفح':'In-browser'}</span><span><Clock size={16}/>{r?'مجاني تجريبي':'Free beta'}</span></div></div><div className="upload"><FileUp size={44}/><h2>{r?'جرّب نموذج الرفع':'Try upload flow'}</h2><input type="file" onChange={e=>setFileName(e.target.files?.[0]?.name||'')}/>{fileName&&<div className="ok"><CheckCircle2 size={15}/>{fileName}</div>}<div className="quick"><button className="btn secondary" onClick={()=>setModal(tools.find(t=>t.id==='split'))}><Scissors size={16}/>{r?'تقسيم':'Split'}</button><button className="btn secondary" onClick={()=>setModal(tools.find(t=>t.id==='rotate'))}><RotateCw size={16}/>{r?'تدوير':'Rotate'}</button><button className="btn secondary" onClick={()=>setModal(tools.find(t=>t.id==='merge'))}><Download size={16}/>{r?'دمج':'Merge'}</button></div></div></section><section><div className="sectionHead"><div><h2>{r?'كل أدوات المستندات في مكان واحد':'All document tools in one place'}</h2><p>{r?'متاح، تجريبي، وقادم قريبًا.':'Available, beta, and coming soon.'}</p></div><div className="filters"><label><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={r?'ابحث عن أداة':'Search tools'}/></label>{['All','PDF','AI','Convert'].map(x=><button className={cat===x?'tab active':'tab'} onClick={()=>setCat(x)} key={x}>{x}</button>)}</div></div><div className="grid">{filtered.map(t=><Card key={t.id} tool={t} lang={lang} onClick={()=>setModal(t)}/>)}</div></section></main><footer><span>© 2026 DocLingo AI</span><span>Privacy · Terms · Contact</span></footer>{modal&&(modal.status==='Available'?<PdfTool tool={modal} lang={lang} onClose={()=>setModal(null)}/>:<Placeholder tool={modal} lang={lang} onClose={()=>setModal(null)}/>)}</div>}
